# Generated by Django 5.2.5 on 2025-09-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDopcion', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDopcion.animal'),
        ),
    ]
