# Generated by Django 5.2.5 on 2025-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='animales/')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
