# Generated by Django 5.2.5 on 2025-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDopcion', '0002_animal_delete_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='tamano',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
